version: '3.8'

services:
  # Redis service
  redis:
    image: redis:7-alpine
    container_name: scalable-api-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Your API service
  api:
    build: .
    container_name: scalable-api
    restart: unless-stopped
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:
